### PR TITLE
syntax, controllers work with updated calibration, optional balance p…

### LINKED ISSUE #50: Balance bot code doesn't work with new motor calibration
motor calibration and signs need to be fixed. 

would be nice also to be able to change balance point over wifi.

### PR DESCRIPTION
**Pull request by stilsota**
**changelog** 
- made balance bot work with new motor calibration standard. (fixed +/- signs) 
- syntax fix (missing semicolon)
- added optional (commented out) PID controller, where the P value updates the balance point of the robot in real time. 

closes #50

### CODE REVIEW

File: examples/balance_bot.cpp [hunk 1]
```diff
@@ -9,8 +9,8 @@
 #include "sensorgo_mpu6050.h"
 
 // UPDATE THESE VALUES
-String WIFI_SSID = "YOUR_SSID";
-String WIFI_PASSWORD = "YOUR_PASSWORD";
+String WIFI_SSID = "WIFI_SSID";
+String WIFI_PASSWORD = "WIFI_PASSWORD";
```
Comment (SwapnilPande) [inline examples/balance_bot.cpp]: I'm assuming you made this change for clarity. Should we change SSID to something else?

File: examples/balance_bot.cpp [hunk 2]
```diff
@@ -207,6 +221,22 @@ void setup()
...
+        balance_point_controller.P = balance_point_params.p;
+        balance_point_controller.I = balance_point_params.i;
+        balance_point_controller.D = balance_point_params.d;
+        balance_point_controller.output_ramp =
+            balance_point_params.output_ramp;
+        balance_point_controller.limit = balance_point_params.limit;
+        balancing_lpf.Tf = balance_point_params.lpf_time_constant;
+        balance_point_controller.reset();
+      });
+    */
```
Comment (SwapnilPande) [inline examples/balance_bot.cpp]: I'd prefer to not leave commented code in the examples, I want the examples to work as soon as you paste it in with no modifications. I think we should decide to include it or not include it at all. 

On that note, it would be very nice to add very clear comments explaining that this is NOT a PID controller, but simply using P to allow the user to adjust the balance point.

**Review by SwapnilPande — CHANGES_REQUESTED** [review]
Overall useful, I just want to keep the example code very clean and self-explanatory.

File: examples/balance_bot.cpp (hunk 1 above)
Comment (stilsota) [reply examples/balance_bot.cpp]: just forgot it was "YOUR_SSID" haha, either one is fine!

File: examples/balance_bot.cpp (hunk 2 above)
Comment (stilsota) [reply examples/balance_bot.cpp]: Hmm not sure, I mostly put it there for the how-to video. we can remove it and I can add it to a video description (i.e. where to find this and paste it into your sketch) so we can leave the main 3 alone

File: examples/balance_bot.cpp (hunk 1 above)
Comment (SwapnilPande) [reply examples/balance_bot.cpp]: Okay, let's leave it at your SSID then

File: examples/balance_bot.cpp (hunk 2 above)
Comment (SwapnilPande) [reply examples/balance_bot.cpp]: I think it's a good thing to include. Hopefully, we'll also support any type of variable in the WEB GUI as well by the time lots of people are using it.

Comment (stilsota) [reply examples/balance_bot.cpp]: ok updated the code and just pushed it. I think this is good to go (sans the API changes you've made)

**Review by SwapnilPande — APPROVED** [review]

**Comment by SwapnilPande** [comment]
@stilsota, I've rebased this on the latest version of the driver. If possible, could you download and run the balance bot example and confirm that it is working as expected? If so, this will be ready to merge into dev.

**Comment by stilsota** [comment]
Just tried it. When I compile it throws this error: 

I have a MotorGo 1.2 plugged in with the 2 PTZ motors. It is showing an up to date branch on feature-50/balance-bot-balance-point-tuning 

resolved - I was flashing out of the wrong directory. 

``` 
/Users/tstilson/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/balance_bot/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `setup()'
/Users/tstilson/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/balance_bot/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0xc): undefined reference to `loop()'
/Users/tstilson/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/balance_bot/libFrameworkArduino.a(main.cpp.o): in function `loopTask(void*)':
/Users/tstilson/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:42: undefined reference to `setup()'
/Users/tstilson/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: /Users/tstilson/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:48: undefined reference to `loop()'
collect2: error: ld returned 1 exit status
*** [.pio/build/balance_bot/firmware.elf] Error 1
===================== [FAILED] Took 38.56 seconds =====================

Environment    Status    Duration
-------------  --------  ------------
balance_bot    FAILED    00:00:38.555
================ 1 failed, 0 succeeded in 00:00:38.555 ================

 *  The terminal process "platformio 'run', '--environment', 'balance_bot'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by stilsota** [comment]
Code is compiling but on balance bot and spin 2 motors examples, but the motor calibrations do not appear to be saving to the board. 

output from spin 2 motors code: 

```
--- Terminal on /dev/cu.usbmodem1301 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
[  3114][E][esp32-hal-spi.c:178] spiAttachSCK(): HSPI Does not have default pins on ESP32S3!
[  3114][E][esp32-hal-spi.c:215] spiAttachMISO(): HSPI Does not have default pins on ESP32S3!
[  3119][E][esp32-hal-spi.c:247] spiAttachMOSI(): HSPI Does not have default pins on ESP32S2!
Starting Sensor Calibration.
MOT: sensor_direction==CW
Rotating forwards
Rotating backwards
Average Zero Electrical Angle: 0.00
Sensor Calibration Done.
Initialized ch0
Starting Sensor Calibration.
MOT: sensor_direction==CW
Rotating forwards
Rotating backwards
Average Zero Electrical Angle: 0.00
Sensor Calibration Done.
Initialized ch1
```

Observed behavior:
- flashed code with bool calibrate = true 
- motors calibrate normally (no issue with motor wires or connections) 
- estimated electrical angle = 0.00 for both motors 
- after calibration, motors lock up and do not spin. 

Troubleshooting steps:
- triple checked encoder wire connections and motor connections 
- try another MotorGo board for spin 2 motors example

**Comment by SwapnilPande** [comment]
Just to confirm, you tried another MotorGo board in your troubleshooting steps?

Looking at the serial output you posted, I'm suspicious that the issue is realted to the SPI errors you see before sensor calibration - we should never be trying to use the default pins. Let me dig into that right now

**Comment by SwapnilPande** [comment]
Ahh I understand the issue. This code should be built against a new version of the motorgo-arduino drivers (in the dev branch in that repo). The names of the pins have changed and that's not been reflected in the main branch yet. 

Sorry about the version mismatching going on here. It's a bit hard to keep track of, but these version mistmatches will not be an issue when:
1. Our board definitions are not changing regularly
2. We submit our board definitions to be part of the Arduino ESP framework (happening in the next few days)

**Comment by SwapnilPande** [comment]
This issue has been addressed by #65, merging these changes into dev.
